include: package:flutter_lints/flutter.yaml

analyzer:
    language:
        strict-casts: true
        strict-inference: false
        strict-raw-types: false

linter:
    rules:
        - prefer_relative_imports
